### PR TITLE
Add Configuration files of 2016 Aoife's Paper

### PR DESCRIPTION
**Pull request by blackbird7112**
### :pencil: Description

**Type:** :rocket: `feature`

Add configuration files from the 2016 paper by Aoife, Sim and Kerzendrof.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [x] Other method (describe)
- [ ] My changes can't be tested (explain why)
Manually run the script

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

### CODE REVIEW

**Comment by andrewfullard** [comment]
Couple of obvious points: you misspelled Kerzendorf, and you should use Aoife's second name, Boyle, in the folder name.

**Comment by epassaro** [comment]
Would be nice to separate the config files from the results in different folders

**Comment by blackbird7112** [comment]
@epassaro I did not understand your comment. Which results are you talking about?

**Comment by blackbird7112** [comment]
If you are referring to the text files, then they are not results. They are input files for the model

**Review by andrewfullard — APPROVED** [review]

**Comment by wkerzendorf** [comment]
can you add @aoifeboyle as a co-author to this commit.

**Comment by blackbird7112** [comment]
@wkerzendorf Added Aoife as a co author to the commit.

**Review by epassaro — APPROVED** [review]

**Pull request merged**
